Fix internal mypy error on Windows (#13153)
When running `pre-commit` on Windows, I get the error below:

```
src\_pytest\_py\error.py:95: error: Invalid index type "Optional[int]" for "dict[int, int]"; expected type "int"  [index]
Found 1 error in 1 file (checked 234 source files)
```

Ignore the error because we do catch the `KeyError` anyway.