test_unittest: skip asynctest for Python 3.11+ (#13777)
asynctest is not supported for Python 3.11+ because `@asyncio.coroutine` was removed in Python 3.11.

Running the test suite with `tox -e py312-asynctest` gives this error:

```
    class _AwaitEvent:
        def __init__(self, mock):
            self._mock = mock
            self._condition = None

>       @asyncio.coroutine
         ^^^^^^^^^^^^^^^^^
E       AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```